# Generated by Django 2.1.5 on 2019-01-23 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0008_auto_20181205_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='url_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='url_active_last_checked',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
