# Generated by Django 2.1.5 on 2019-01-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0009_auto_20190123_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url_active_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
