# Generated by Django 2.1.2 on 2018-11-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
