# Generated by Django 2.1.2 on 2018-11-27 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortener_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener_app', '0005_shorturl_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccess',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('apikey',
                 models.CharField(
                     default=shortener_app.models.generate_random_apikey,
                     max_length=64,
                     unique=True)),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
