# Generated by Django 2.1.2 on 2018-11-28 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0006_apiaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrlStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(default=0)),
                ('aggregated_datetime', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('short_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shortener_app.ShortUrl')),
            ],
        ),
    ]
