# Generated by Django 2.1.2 on 2018-12-05 23:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0007_shorturlstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrlLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=16, null=True)),
                ('os', models.CharField(blank=True, max_length=16, null=True)),
                ('country_code', models.CharField(blank=True, max_length=4, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('referer', models.CharField(blank=True, max_length=256, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256, null=True)),
                ('short_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shortener_app.ShortUrl')),
            ],
        ),
        migrations.RemoveField(
            model_name='shorturlstats',
            name='short_url',
        ),
        migrations.DeleteModel(
            name='ShortUrlStats',
        ),
    ]
